bdHakimaru/urls.py
from django.urls import path
from bdHakimaru.views import  Home, nueva_pelea, consultar_peleas, consultar_demonios, nuevo_monstruo, nuevo_lugar, objeto_list, nuevo_objeto, borrar_objeto,imprimir_monstruos


urlpatterns = [
    path('',Home.as_view(),name='Home'),
    path('bdHakimaru/new', nueva_pelea.as_view(), name = 'nueva_pelea'),
    path('bdHakimaru/', consultar_demonios.as_view(),name = 'consultar_demonios'),
    path('bdHakimaru/peleas', consultar_peleas.as_view(),name = 'consultar_peleas'),
    path('bdHakimaru/new_monster',nuevo_monstruo.as_view(),name = 'nuevo_monstruo'),
    path('bdHakimaru/new_place',nuevo_lugar.as_view(), name = 'nuevo_lugar'),
    path('bdHakimaru/objeto_list',objeto_list.as_view(), name = 'objetos_dororo'),
    path('bdHakimaru/nuevo_objeto',nuevo_objeto.as_view(), name = 'nuevo_objeto'),
    path('bdHakimaru/delete/<int:pk>',borrar_objeto.as_view(), name = 'borrar_objeto'),
    path('bdHakimaru/imprimir',imprimir_monstruos,name = 'imprimir_monstruos'),
]

hakimaru/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('',include(('bdHakimaru.urls','bdHakimaru'),namespace='bdHakimaru')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

bdHakimaru/models.py
from django.db import models
# Create your models here.

class Lugar(models.Model):
    nombre = models.CharField(max_length=50,)
    imagen = models.ImageField(upload_to="lugares", null = True)
    def save(self):
        super(Lugar,self).save()
    def __str__(self):
        return self.nombre

class Pieza(models.Model):
    nombre = models.CharField(max_length=50)
    def __str__(self):
        return '{}'.format(self.nombre)

class Monstruo(models.Model):
    nombre = models.CharField(max_length=30,)
    imagen = models.ImageField(upload_to="monstruos", null = True)
    pieza = models.ForeignKey(
        Pieza,
        on_delete = models.CASCADE,
    )
    lugar = models.ForeignKey(
        Lugar,
        on_delete = models.CASCADE,
    )
    def save(self):
        super(Monstruo,self).save()
    class Meta:
        verbose_name_plural = 'Monstruos'
    
    def __str__(self):
        return '{}'.format(self.nombre)


class Pelea(models.Model):
    lugar = models.ForeignKey(
        Lugar,
        on_delete = models.CASCADE
    )
    monstruo = models.ForeignKey(
        Monstruo,
        on_delete = models.CASCADE
    )
    def save(self):
        super(Pelea,self).save()
    class Meta:
        verbose_name_plural = 'Peleas'
    
    def __str__(self):
        return '{}'.format(self)

class Objeto(models.Model):
    nombre = models.CharField(max_length=30,)
    ROBO = 'Robo'
    COMPRA = 'Compra'
    REGALO = 'Regalo'
    ESTADOS_CHOICES = [
        (ROBO, 'Robo'),
        (COMPRA, 'Compra'),
        (REGALO, 'Regalo'),
    ]
    origen = models.CharField(
        max_length=20,
        choices=ESTADOS_CHOICES,
        default=ROBO,
    )

    def save(self):
        super(Objeto,self).save()
    class Meta:
        verbose_name_plural = 'Objetos'
    
    def __str__(self):
        return '{}'.format(self)

bdHakimaru/forms.py
from django import forms
from bdHakimaru.models import Monstruo, Pelea, Pieza, Lugar, Objeto

class pelea_form(forms.ModelForm):
    class Meta:
        model = Pelea
        fields = ['lugar','monstruo']
        labels = {'lugar': 'Lugar' , 'monstruo':'Monstruo'}
        #widget = {'lugar': forms.TextInput(),'monstruo':forms.TextInput()}
        def __init__(self,*args, **kwargs):
            super().__init__(*args, **kwargs)
            for field in iter(self.fields):
                self.fields[field].widget.attrs.update({
                    'class': 'form-control'
                })

class monstruo_form(forms.ModelForm):
    class Meta:
        model = Monstruo
        fields = ['nombre','imagen','pieza','lugar']
        labels = {'nombre':'Nombre','imagen':'Imagen','pieza':'Pieza','lugar':'Lugar'}
        def __init__(self,*args, **kwargs):
            super().__init__(*args, **kwargs)
            for field in iter(self.fields):
                self.fields[field].widget.attrs.update({
                    'class': 'form-control'
                })

class lugar_form(forms.ModelForm):
    class Meta:
        model = Lugar
        fields = ['nombre','imagen']
        labels = {'nombre':'Nombre', 'imagen':'Imagen'}
        def __init__(self,*args, **kwargs):
            super().__init__(*args, **kwargs)
            for field in iter(self.fields):
                self.fields[field].widget.attrs.update({
                    'class': 'form-control'
                })

class objetos_form(forms.ModelForm):
    class Meta:
        model = Objeto
        fields = ['nombre','origen']
        labels = {'nombre':'Nombre', 'origen':'Origen'}
        def __init__(self,*args, **kwargs):
            super().__init__(*args, **kwargs)
            for field in iter(self.fields):
                self.fields[field].widget.attrs.update({
                    'class': 'form-control'
                })

bdHakimaru/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from bdHakimaru.models import Lugar, Pieza, Monstruo, Pelea, Objeto
from bdHakimaru.forms import pelea_form, monstruo_form, lugar_form, objetos_form
from django.http import HttpResponse

class Home(generic.View):
    model = Pieza
    template_name = 'bdHakimaru/home.html'
    context_object_name = 'obj'        

    def get(self, request):
        piezas = Pelea.objects.filter().count()
        print(piezas)
        context = {'piezas':piezas}
        return render(request, self.template_name,context)

class consultar_demonios(generic.ListView):
    model = Monstruo
    template_name = 'bdHakimaru/monstruo_list.html'
    context_object_name = 'obj'

class consultar_peleas(generic.ListView):
    model = Pelea
    template_name = 'bdHakimaru/consultar_peleas.html'
    context_object_name = 'obj'
    success_url=reverse_lazy("bdHakimaru:Home")

class nueva_pelea(generic.CreateView):
    model = Pelea
    context_object_name = 'obj'
    form_class = pelea_form
    template_name = 'bdHakimaru/nueva_pelea.html'
    success_url=reverse_lazy("bdHakimaru:consultar_peleas")

class nuevo_monstruo(generic.CreateView):
    model = Monstruo
    context_object_name = 'obj'
    form_class = monstruo_form
    template_name = 'bdHakimaru/nuevo_monstruo.html'
    success_url=reverse_lazy("bdHakimaru:consultar_demonios")

class nuevo_lugar(generic.CreateView):
    model = Lugar
    context_object_name = 'obj'
    form_class = lugar_form
    template_name = 'bdHakimaru/nuevo_lugar.html'
    success_url=reverse_lazy("bdHakimaru:Home")

class nuevo_objeto(generic.CreateView):
    model = Objeto
    context_object_name = 'obj'
    form_class = objetos_form
    template_name = 'bdHakimaru/nuevo_objeto.html'
    success_url=reverse_lazy("bdHakimaru:objetos_dororo")

class objeto_list(generic.ListView):
    model = Objeto
    templane_name = 'bdHakimaru/objetos_list.html'
    context_object_name = 'obj'

class borrar_objeto(generic.DeleteView):
    model = Objeto
    template_name = 'bdHakimaru/borrar_objeto.html'
    context_object_name = 'obj'
    success_url = reverse_lazy("bdHakimaru:objetos_dororo")

def imprimir_monstruos(self):
    import io
    from reportlab.platypus import SimpleDocTemplate, Paragraph, TableStyle
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter
    from reportlab.platypus import Table

    response = HttpResponse(content_type='application/pdf')
    buff = io.BytesIO()
    doc = SimpleDocTemplate(buff,
                            pagesize=letter,
                            rightMargin=40,
                            leftMargin=40,
                            topMargin=60,
                            bottomMargin=18,
                            )
    monstruos = []
    styles = getSampleStyleSheet()
    header = Paragraph("Listado de monstruos", styles['Heading1'])
    monstruos.append(header)
    headings = ('Id', 'Nombre', 'Pieza')
    todosmonstruos = [(p.id, p.nombre, p.pieza.nombre)
                        for p in Monstruo.objects.all().order_by('pk')]
   
    t = Table([headings] + todosmonstruos)
    t.setStyle(TableStyle(
        [
            ('GRID', (0, 0), (3, -1), 1, colors.dodgerblue),
            ('LINEBELOW', (0, 0), (-1, 0), 2, colors.darkblue),
            ('BACKGROUND', (0, 0), (-1, 0), colors.dodgerblue)
        ]
    ))

    monstruos.append(t)
    doc.build(monstruos)
    response.write(buff.getvalue())
    buff.close()
    return response

bdHakimaru/templates/bdHakimaru/borrar_objeto.html
{% extends 'style.html' %}
{% load static %}

{% block title %}
<title>Castigar a Dororo</title>
{% endblock title %}

    <body>
        {% block body %}
       
        <form method="POST" >

            {% csrf_token %}
            
            <div id="capa1p1" style="vertical-align: middle; align-content: center; ">
                <center>
                    <h3 style="color: white; font-family: 'roboto''condensed';">¿Deseas castigar a Dodoro?</h3>

                    <div  style="align-self: center; align-content: center; align-items: center;">
                        <img style="margin-bottom: 70px; " width="320px" height="306px" src="{% static 'images/dororoLlorando.png' %}"  alt='Dororo Llorando Que Sad'>
                    </div>
                        <button id="btnWh" type="submit" class="waves-effect waves-light btn red red" style="align-self: center;">
                            <span class="fa fa-undo">CASTIGAR</span>
                        </button>
                        <a id="btnWh" class="waves-effect waves-light btn red"  href = "{% url 'bdHakimaru:objetos_dororo'%}">NO CASTIGAR</a>
                </center>
            </div>
        </form>

        {% endblock body %}
    <body>

bdHakimaru/templates/bdHakimaru/consultar_peleas.html
{% extends 'style.html' %}
{% block body %}
<head>
<header style="width: 100%; height:60px;">
  <div style="margin-top: 15px;  width: 100%; text-align: center;">
  <a id="ahead" href="{% url 'bdHakimaru:Home' %}">
    Hyakkimaru
  </a>
</div>
</header>
{% block title %}
<title>Registro de combates</title>
{% endblock title %}
</head>
<body>
  <div style="color: black;">
<div class="tablaConsulta" > 
        
    <!--titulos--> 
    <table id="tabla" class="highlight centered"> <thead> <tr> 
     <th>Lugar de la pelea</th>
     <th>Monstruo vencido</th>
     <th>Pieza obtenida</th>
    <th > </th>
    
  
  </tr>
  </thead>
  <body>
    <div id="capa3"></div>
    <thead></thead>
    {% for item in obj %}
    <tr>
       <!--Datos--> 
      <td><img  src = "{{item.lugar.imagen.url}}" width="100" height="100"><br><br>{{item.lugar.nombre}}</td>
      <td><img  src = "{{item.monstruo.imagen.url}}" width="100" height="100"><br><br>{{item.monstruo.nombre}}</td>
      <td>{{item.monstruo.pieza}}</td>
      <td>   
    </td>
    </tr> {% endfor %} </table>  </tbody> </div>
  </div>
    <div id="capa4">
        <a id="btnWhInf" class="waves-effect waves-light btn red" href = "{% url 'bdHakimaru:nueva_pelea' %}">Nueva pelea</a>
      </div>
  
{% endblock body %}
</div>
<body>

bdHakimaru/templates/bdHakimaru/home.html
{% extends 'style.html' %}
{% load static %}
<html>
<head>
    {% block title %}
        <title>Hyakkymaru: Página Principal</title>
    {% endblock title %}

<body class="bod1" > 
    <div style="background-color: black;">
    {% block body %}
    <div style="padding-top: 20px;">
        <p id="tl">Hyakkimaru</p>
    </div>   

    <div id="capa1">
        <img width="166" height="427.5" src="{% static 'images/hyakki.jpg' %}"  alt='Hyakkimaru'>
    </div>

    <div id="capa2">
        <table>
            <tr>
                <td>
                    <a id="btnWh" class="waves-effect waves-light btn red" href = "{% url 'bdHakimaru:consultar_peleas' %}">PELEAS</a>
                </td>
                <td>
                    <a id="btnWh" class="waves-effect waves-light btn red" href = "{% url 'bdHakimaru:consultar_demonios'%}">DEMONIOS</a>
                </td>
                <td>
                    <a id="btnWh" class="waves-effect waves-light btn red"  href = "{% url 'bdHakimaru:objetos_dororo'%}">DORORO</a>
                </td>
                <td>
                    <a id="btnWh" class="waves-effect waves-light btn red"  href = "{% url 'bdHakimaru:imprimir_monstruos'%}">REPORTE EN PDF</a>
                </td>
            </tr>
        </table>
    </div>

    <div id="con">
        <p>{{ piezas }} / 48</p>
    </div>
    {% endblock body %}
</div>
</body>





</html>

bdHakimaru/templates/bdHakimaru/monstruo_list.html
{% extends 'style.html' %}
{% block body %}
<head>
  <header style="width: 100%; height:60px;">
    <div style="margin-top: 15px;  width: 100%; text-align: center;">
    <a id="ahead" href="{% url 'bdHakimaru:Home' %}">
      Hyakkimaru
    </a>
  </div>
  </header>
{% block title %}
<title>Demonios</title>
{% endblock title %}
</head>
<div class="tablaConsulta" > 
        
    <!--titulos--> 
    <table id="tabla" class="highlight centered"> <thead> <tr> 
    <th style="width: 5%;">ID</th>
    <th>Nombre</th>
    <th>Foto</th>
    <th>Pieza que posee</th>
    <th>Fue visto en</th>
    
  
  </tr>
  </thead>
  <body >

  <div id="capa3" style="color: black;">
    {% for item in obj %}
    <tr>
       <!--Datos--> 
      <td>{{item.id}}</td>
      <td>{{item.nombre}}</td>
      <td><img  src = "{{item.imagen.url}}" width="100" height="100"></td>
      <td> {{item.pieza.nombre}}</td>
      <td><img  src = "{{item.lugar.imagen.url}}" width="100" height="100"><br>{{item.lugar.nombre}}</td>
      <td>   
    </td>
    </tr> {% endfor %} </table>  </tbody> </div>
  </div>

  <div class="fixed-action-btn"> 

    <a style="margin-right: 10px;  margin-bottom: 30px;"
    class="btn-floating btn-large waves-effect waves-light red darken-2 direction-center btn" href = "{% url 'bdHakimaru:nuevo_monstruo' %}">
      <i class="material-icons">add</i>
  </a>
  </div>

{% endblock body %}

</body>

bdHakimaru/templates/bdHakimaru/nueva_pelea.html
<html>

  <title>Peleas</title>

<body>


   <form  method = "POST" enctype="multipart/form-data">
     
  {% csrf_token %} <!--Toquén de seguirad para django -->

 
  {{ form.as_p }}
 
      <button type="submit" class="btn waves-effect waves-light green ">
        Guardar
      </button>
<br><br>
    </form>
  </body>

    </html>

bdHakimaru/templates/bdHakimaru/nuevo_lugar.html
 <form  method = "POST" enctype="multipart/form-data">
     
    
  {% csrf_token %} <!--Toquén de seguirad para django -->

 
  {{ form.as_p }}
 
      <button type="submit" class="btn waves-effect waves-light green ">
        Guardar
      </button>
<br><br>
    </form>

bdHakimaru/templates/bdHakimaru/nuevo_monstruo.html
<html>
  <title>INGRESAR DEMONIO</title>
  
  <body>
    
    <div style="padding-top: 20px;">
      <p id="tll">Ingresar Demonio</p>
  </div>  

    <div id="centerDiv" style="margin-top: 10px;">
    <form method = "POST" enctype="multipart/form-data">
    
      {% csrf_token %} <!--Toquén de seguirad para django -->
     
      {{ form.as_p }}
     
          <button type="submit" class="btn waves-effect waves-light green ">
            Guardar
          </button>
    <br><br>
    </form>
  </div>
    

</body>

 
<html>

bdHakimaru/templates/bdHakimaru/nuevo_objeto.html
<html>
  <title>INGRESAR OBJETO</title>
  
  <body>
    
    <div style="padding-top: 20px;">
      <p id="tll">Ingresar Objeto</p>
  </div>  

    <div id="centerDiv" style="margin-top: 10px;">
    <form method = "POST" enctype="multipart/form-data">
    
      {% csrf_token %} <!--Toquén de seguirad para django -->
     
      {{ form.as_p }}
     
          <button type="submit" class="btn waves-effect waves-light green ">
            Guardar
          </button>
    <br><br>
    </form>
  </div>
    

</body>

 
<html>

bdHakimaru/templates/bdHakimaru/objeto_list.html
{% extends 'style.html' %}
{% block body %}
<head>
  <header style="width: 100%; height:60px;">
    <div style="margin-top: 15px;  width: 100%; text-align: center;">
    <a id="ahead" href="{% url 'bdHakimaru:Home' %}">
      Hyakkimaru
    </a>
  </div>
  </header>
{% block title %}
<title>Objetos de Dororo</title>
{% endblock title %}
</head>

<div class="tablaConsulta" > 
        
    <!--titulos--> 
    <table id="tabla" class="highlight centered"> <thead> <tr> 
    <th>Nombre</th>
    <th>Origen</th>
    <th>Acciones</th>
  </tr>
  </thead>
  <body >

  <div id="capa3" style="color: black;">
    {% for item in obj %}
    <tr>
       <!--Datos--> 
      <td>{{item.nombre}}</td>
      <td>{{item.origen}}</td>
      <td> <a id="btnWh1" class="waves-effect waves-light btn red" href = "{% url 'bdHakimaru:borrar_objeto' item.id%}">CASTIGAR</a></td>
    </tr> {% endfor %} </table>  </tbody> </div>
  </div>

  <div class="fixed-action-btn"> 

    <a style="margin-right: 10px;  margin-bottom: 30px;"
    class="btn-floating btn-large waves-effect waves-light red darken-2 direction-center btn" href = "{% url 'bdHakimaru:nuevo_objeto' %}">
      <i class="material-icons">add</i>
  </a>
  </div>


{% endblock body %}

</body>

bdHakimaru/templates/style.html
<html>

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" rel="stylesheet" >
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Ruda|Squada+One&display=swap" rel="stylesheet">
    
    {% block title %}

    {% endblock title %}

    <style>
        body{
            background-color: black;
        }
        body.bod2{
            background-color: white;
        }
        #tbod{
            background-color: gray;
        }
        #tl {
          color:   white;
          text-align: center;
          font-size: 50px;
          font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        } 
        #capa1 {
            position: absolute; 
            text-align:justify;  
            left: 50%; 
            top: 30%; 
            margin-top: -100px; 
            margin-left: -90px; 
            }
        #capa1p1 { 
            margin-top: 80px; 
            }
        #capa2 {
            position: absolute; 
            text-align:justify;
            left: 50%; 
            top: 30%; 
            margin-top: 220px; 
            margin-left: -330px;
            }
        #capa3 {
            position: absolute; 
            text-align:justify;
            } 
        #capa4 {
            position: absolute; 
            text-align:justify;
            left: 80%; 
            bottom: 10%; 
            } 
        #btnWh {
            font-weight: 500;
            color: white;
            width: 160px;
            margin-right: 10px;
            }
        #btnWh1 {
            font-weight: 500;
            color: white;
            width: 160px;
            }
        #btnWhInf {
            position:fixed; 
            font-weight: 500;
            color: white;
            width: 160px;
            left: 80%;
            } 
        #con {
            position: absolute;
            font-size: 70px;
            color: white;
            text-align: justify;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            text-align:justify;
            left: 50%; 
            top: 30%; 
            margin-top: 330px; 
            margin-left: -55px;
            }     
        #centerDiv{
           position: absolute;
           width: 500px;
           left: 5%;
        }
        #tll {
          color:   white;
          font-size: 50px;
          font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
          margin-left: 70px;
        } 
        #tabla{
           color: white;
        }
        #ahead{
            text-decoration: none;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
            font-size: 30px;
            color: white;
            font-weight: bold;
        }
        </style>
    </head>
    
</head>
<body>
    {% block body %}

    {% endblock body %}

</body>
</html>

bdHakimaru/templates/style2.html
<html>

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    {% block title %}

    {% endblock title %}

    <style>
        body{
            background-color: white;
        }
        #centerDiv{
           position: absolute;
           width: 500px;
           left: 5%;
        }
        #tll {
          color:   black;
          font-size: 50px;
          font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
          margin-left: 70px;
        } 
        #tabla{
           color: white;
        }
        </style>
    </head>
    
</head>
<body>
    {% block body %}

    {% endblock body %}

</body>
</html>